# Generated by Django 2.2.7 on 2019-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='user',
        ),
        migrations.AddField(
            model_name='contest',
            name='end_date_str',
            field=models.CharField(default='no', max_length=500),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_date_str',
            field=models.CharField(default='no', max_length=500),
        ),
    ]
