# Generated by Django 2.2.7 on 2019-11-21 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoapp', '0002_auto_20191116_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='user',
            field=models.ManyToManyField(related_name='contest', through='photoapp.PhotoUpload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
