# Generated by Django 2.2.7 on 2019-11-23 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_auto_20191121_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoupload',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload', to='photoapp.Contest'),
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
