# Generated by Django 2.2.7 on 2019-11-23 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0004_auto_20191123_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='end_date_str',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='start_date_str',
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload', to='photoapp.Contest'),
        ),
        migrations.AlterField(
            model_name='photoupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
