# Generated by Django 2.2.7 on 2019-11-27 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoapp', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TXNID', models.CharField(max_length=70, verbose_name='TNX ID')),
                ('BANKTXNID', models.CharField(blank=True, max_length=60, null=True, verbose_name='BANK TXN ID')),
                ('ORDERID', models.CharField(max_length=70, verbose_name='ORDER ID')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('STATUS', models.CharField(max_length=30, verbose_name='STATUS')),
                ('TXNTYPE', models.CharField(blank=True, max_length=10, null=True, verbose_name='TNX TYPE')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=20, null=True, verbose_name='GATEWAY NAME')),
                ('RESPCODE', models.CharField(max_length=20, verbose_name='STATUS')),
                ('RESPMSG', models.TextField(max_length=600, verbose_name='RESP MSG')),
                ('BANKNAME', models.CharField(blank=True, max_length=600, null=True, verbose_name='BANK NAME')),
                ('MID', models.CharField(max_length=40)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAYMENT MODE')),
                ('REFUNDAMT', models.FloatField(default=0, verbose_name='RFUND AMOUNT')),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('photo_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload_payment', to='photoapp.PhotoUpload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
